"""Add Agriculture_shops schema

Revision ID: 0893515a888e
Revises: a5bcdcc43f1f
Create Date: 2024-10-28 12:57:39.178416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0893515a888e'
down_revision = 'a5bcdcc43f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agriculture_shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(15), nullable=False),
    sa.Column('district', sa.String(length=10), nullable=False),
    sa.Column('tehsil', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('town', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('agriculture_shops')
    # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('newsletter',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
#     sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
#     sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
#     sa.PrimaryKeyConstraint('id', name='newsletter_pkey')
#     )
#     op.drop_table('agriculture_shops')
#     # ### end Alembic commands ###
