"""empty message

Revision ID: 29cc78b5f86b
Revises: 50c474beab5a
Create Date: 2024-10-28 13:33:49.641643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cc78b5f86b'
down_revision = '50c474beab5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agriculture_shops', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('contact',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               nullable=False)
        batch_op.alter_column('district',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('tehsil',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('town',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agriculture_shops', schema=None) as batch_op:
        batch_op.alter_column('town',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('tehsil',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('district',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('contact',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
