"""empty message

Revision ID: 462eadc28e2d
Revises: d1aaeb0a90d8
Create Date: 2024-10-28 15:30:43.554625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462eadc28e2d'
down_revision = 'd1aaeb0a90d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solar_shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('tehsil', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('town', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solar_shops')
    # ### end Alembic commands ###
