"""Add Agriculture_shops schema 1

Revision ID: 50c474beab5a
Revises: 0893515a888e
Create Date: 2024-10-28 13:16:32.341283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c474beab5a'
down_revision = '0893515a888e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agriculture_shops', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('district',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('tehsil',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('town',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agriculture_shops', schema=None) as batch_op:
        batch_op.alter_column('town',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('tehsil',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('district',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('contact',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
