"""empty message

Revision ID: 8f744a336bac
Revises: a7c7f20d4747
Create Date: 2024-10-30 14:52:52.892776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f744a336bac'
down_revision = 'a7c7f20d4747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('vehicles_created_by_fkey', type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('vehicles_created_by_fkey', 'users', ['created_by'], ['user_id'])

    # ### end Alembic commands ###
