"""empty message

Revision ID: 9a2521d073a4
Revises: 3220091a03c2
Create Date: 2024-10-29 11:12:26.742549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2521d073a4'
down_revision = '3220091a03c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('union_councils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Union_council_name', sa.String(length=100), nullable=False),
    sa.Column('Union_council_discription', sa.String(length=200), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('union_councils')
    # ### end Alembic commands ###
