"""Add Newsletter schema

Revision ID: a5bcdcc43f1f
Revises: ab6f9cd863e0
Create Date: 2024-10-28 12:34:15.640625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5bcdcc43f1f'
down_revision = 'ab6f9cd863e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=120),
               nullable=True,
               existing_server_default=sa.text("'Unknown'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=120),
               nullable=False,
               existing_server_default=sa.text("'Unknown'::character varying"))

    op.drop_table('newsletter')
    # ### end Alembic commands ###
