"""empty message

Revision ID: d1aaeb0a90d8
Revises: 29cc78b5f86b
Create Date: 2024-10-28 14:29:53.231806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1aaeb0a90d8'
down_revision = '29cc78b5f86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agriculture_shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=False))
        batch_op.drop_column('contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agriculture_shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
